export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_TOVAR_DATA: 'SET_TOVAR_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_TOVAR_DATA: 'RESET_TOVAR_DATA',
	ADD_TO_CART: 'ADD_TO_CART',
	INCREASE_QUANTITY: 'INCREASE_QUANTITY',
	DECREASE_QUANTITY: 'DECREASE_QUANTITY',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
};
